name: Publish NuGet Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build, Test, and Pack
      run: dotnet build --configuration Release && dotnet test --configuration Release --no-build && dotnet pack --configuration Release --no-build --output ./nuget

    - name: Publish NuGet package
      run: dotnet nuget push ./nuget/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
